### ISSUE TITLE
Unable to read NEXTCLOUD_DATA_DIR

### ISSUE THREAD

**Issue by NiftyMist** [evertramos/docker-nextcloud-letsencrypt#12]
I have been banging my head around this.  I've made some changes to my set up due to a typo in my nextcloud_data_dir path.  Everything was working before.  The new typoed path was created with no issues.  However I was not happy. with the setup.  So I removed everything to start again to correct the issue.  But now I cannot get nextcloud to read the data-dir on ubuntu 18.04.  Do you  have any recommendations?

**Comment by evertramos** [comment]
Hello @NiftyMist!

Yes, I might have a recommendation...

This will might be because of folder permissions, I think. So you can try to fix it the UID and GID, or...

Remove the new folder (without the typo) you created, let´s the container create the folder structure, than you move the files wherever it fits.
 
Give it a try!

**Comment by NiftyMist** [comment]
I've verified permissions already.  I've even gone as far to make the directory wide open with `chmod -r 777 /path/to/dir` with now joy.  No sticky bits nothing.  I've also removed the directory as recommended with no success.

**Comment by ordilibre** [comment]
Hi,

Sorry if the problem is no longer current, but I found the reason for this problem, and at the same time, the solution.

The reason is the misunderstanding of the role of a variable named in an unclear manner.
**NEXTCLOUD_DATA_DIR** is used to change the default directory of data _ inside_ the container, while the comment in the environment file suggests that it makes it possible to define the host storage directory, _ outside_ the container.

The externalization of this directory requires the declaration of an additional volume attached to the internal directory.

The correction stand in two lines inside **docker-compose.yml** :
...
```
     volumes:
       - ${LOCAL_DATA_DIR}:/var/www/html
       - ${LOCAL_CONF_DIR}:/var/www/html/config
       - ${LOCAL_APPS_DIR}:/var/www/html/apps
# Expose inner data dir to the host filesystem
       - ${NEXTCLOUD_DATA_DIR}:/var/www/html/data
     environment:
       NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
       NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
# Remove unused except if data dir is changed inside container
# in this case, set and use another variable name like
# NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_INNER_DATA_DIR}
       NEXTCLOUD_TABLE_PREFIX: ${NEXTCLOUD_TABLE_PREFIX}
       NEXTCLOUD_TRUSTED_DOMAINS: ${LETSENCRYPT_HOST}
```
...

I hope this will help other users.
